name: Docker build image
run-name: "Build and push Docker image for ${{ github.event_name }} on ${{ github.ref_name }} by ${{ github.actor }}"

on: push

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Print out hello-world
        run: echo "Hello, world."
      - name: Check out repository
        uses: actions/checkout@v3
      - name: list files and directory
        run: ls
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: echo "SHORTENED_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT
        id: hsh-calc
        env:
          GITHUB_SHA: ${{ github.sha }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/academy-learnhub-api:${{ github.ref_name }}-${{ steps.hsh-calc.outputs.SHORTENED_SHA }}
        env:
          GITHUB_SHA: ${{ github.sha }}