name: Docker build image

on: push

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Echo hello-world
        run: echo "Hello, world."
      - name: กูอยู่ที่ไหนวะเนี่ย
        run: pwd
      - name: ไหนมีของอะไรบ้างวะ
        run: ls
      - name: Check out
        uses: actions/checkout@v3